# Generated by Django 3.0.8 on 2020-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('productcost', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='')),
                ('productquantity', models.IntegerField()),
            ],
        ),
    ]
