# Generated by Django 3.0.8 on 2021-06-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(default='static/images/3lions.jpeg', upload_to='static/images'),
        ),
    ]
